### ISSUE TITLE
Get an error when batchsize is set greater than 1

### ISSUE THREAD

**Issue by agate106k** [zyn213/TempRMOT#9]
@zyn213 
Hi, I really admire your outstanding work and am very interested in it. However, I have a question about configuration in the training phases.
Why do I get an error when batch size is set to greater than 1?
In case I try batch size = 1, it works for my environment. However, I got an error below when I set a batch size greater than 1.

 I got the same issue in the RMOT repository.
The issue below is closed, but it still has the same issue for me.
https://github.com/wudongming97/RMOT/issues/20

```[rank0]: Traceback (most recent call last):
[rank0]:   File "main.py", line 361, in <module>
[rank0]:     main(args)
[rank0]:   File "main.py", line 331, in main
[rank0]:     train_stats = train_func(
[rank0]:   File "/mnt/mydisk/TempRMOT/engine.py", line 119, in train_one_epoch_rmot
[rank0]:     outputs = model(data_dict)
[rank0]:   File "/home/kapikei/.pyenv/versions/3.8.10/envs/RMOT-8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/kapikei/.pyenv/versions/3.8.10/envs/RMOT-8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/kapikei/.pyenv/versions/3.8.10/envs/RMOT-8/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1593, in forward
[rank0]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank0]:   File "/home/kapikei/.pyenv/versions/3.8.10/envs/RMOT-8/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1411, in _run_ddp_forward
[rank0]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank0]:   File "/home/kapikei/.pyenv/versions/3.8.10/envs/RMOT-8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/kapikei/.pyenv/versions/3.8.10/envs/RMOT-8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/mydisk/TempRMOT/models/transrmot_pro.py", line 887, in forward
[rank0]:     frame.requires_grad = False
[rank0]: AttributeError: 'list' object has no attribute 'requires_grad'
```

**Comment by zyn213** [comment]
Currently, the code of TempRMOT and TransRMOT only support the setting of batch_size = 1.

**Comment by agate106k** [comment]
Thank you for your reply!
I'm looking forward to the compatible version!
